repos:
  # Rust-specific hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        name: Markdown Lint
        entry: markdownlint
        language: node
        types: [markdown]
        stages: [pre-commit]
        args: ["--fix"]

  # TOML formatting
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        name: TOML Formatter
        args: [--autofix]
        stages: [pre-commit]

  # Environment and secret scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        entry: detect-secrets-hook
        language: python
        stages: [pre-push]

  # Custom hooks
  - repo: local
    hooks:
      - id: update-changelog
        name: Update Changelog
        entry: ./scripts/update_changelog.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: cargo-audit
        name: Cargo Audit
        entry: cargo audit
        language: system
        types: [rust]
        pass_filenames: false

      - id: rust-fmt
        name: Rust Format
        entry: cargo fmt --all --check
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-commit]

      - id: rust-clippy
        name: Rust Clippy
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

# Global configuration
default_language_version:
  python: python3.9

default_stages: [pre-commit, pre-push]
fail_fast: true

minimum_pre_commit_version: "2.20.0"
