[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src", "rust-analysis"]
profile = "default"

[target.x86_64-apple-darwin]
linker = "clang"
ar = "llvm-ar"

[build]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-Wl,-dead_strip",
    "-W", "missing-docs",
    "-W", "rust-2018-idioms",
    "-W", "unused-imports",
]

[profile.dev]
opt-level = 1
debug = true
incremental = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true  # Reduces binary size

[profile.test]
opt-level = 1
debug = true
overflow-checks = true
