[build]
rustflags = [
  "-C",
  "target-cpu=native",
  "-C",
  "link-arg=-Wl,-dead_strip",
  "-W",
  "missing-docs",
  "-W",
  "rust-2018-idioms",
  "-W",
  "unused-imports"
]

[profile.dev]
debug = true
incremental = true
opt-level = 1

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true  # Reduces binary size

[profile.test]
debug = true
opt-level = 1
overflow-checks = true

[target.x86_64-apple-darwin]
ar = "llvm-ar"
linker = "clang"

[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src", "rust-analysis"]
profile = "default"
