[alias]
setup = "run --package podcast_crawler --bin setup"
migrate = "run --package podcast_crawler --bin migrate"
dev = "run --package podcast_crawler"

[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[env]
RUST_LOG = "debug"
RUST_BACKTRACE = "1"
